namespace ToolEngine.Llm.Models;

/// <summary>
/// Result of a pre-flight scope classification call made by
/// <c>AgentScopeClassifier</c> before entering the main orchestration loop.
/// </summary>
public sealed record ScopeClassification(
    /// <summary>
    /// <c>true</c> when the entire user request is outside the domain of
    /// available tools. The orchestrator should return
    /// <see cref="AgentResult.OutOfScope"/> immediately; no tool loop entered.
    /// </summary>
    bool     IsFullyOutOfScope,

    /// <summary>
    /// The portion of the user's request that can be addressed by available
    /// tools. <c>null</c> only when <see cref="IsFullyOutOfScope"/> is <c>true</c>.
    /// When the request was entirely in scope this equals the original text.
    /// When mixed it contains only the tool-relevant sub-request(s).
    /// </summary>
    string?  InScopePortion,

    /// <summary>
    /// Each distinct sub-request that could not be mapped to any available tool.
    /// Empty when the entire request was in scope.
    /// </summary>
    string[] OutOfScopeParts,

    /// <summary>
    /// Human-readable refusal message generated by the classifier when
    /// <see cref="IsFullyOutOfScope"/> is <c>true</c>. Ready to return
    /// directly to the caller. <c>null</c> otherwise.
    /// </summary>
    string?  RefusalMessage,

    /// <summary>
    /// Token usage consumed by the classification LLM call.
    /// Must be recorded in the session immediately so the cumulative
    /// <c>TokensUsed</c> counter reflects the true cost — including the
    /// pre-flight call — before the budget gate is checked for the main loop.
    /// <see cref="LlmUsage.Zero"/> when classification was bypassed (disabled,
    /// no tools, or fail-open fallback).
    /// </summary>
    LlmUsage Usage)
{
    /// <summary>Convenience factory — ScopeGuard disabled; request passes through.</summary>
    public static ScopeClassification FullyInScope(string originalText) =>
        new(false, originalText, [], null, LlmUsage.Zero);

    /// <summary>Convenience factory — fail-open fallback when classification parsing fails.</summary>
    public static ScopeClassification FailOpen(string originalText) =>
        new(false, originalText, [], null, LlmUsage.Zero);
}
