namespace ToolEngine.Integration.Tests.Compliance;

using ToolEngine.Core.Domain.Common;
using ToolEngine.Core.Domain.Enums;
using ToolEngine.Integration.Tests.Infrastructure;
using ToolEngine.Tools.Abstractions.Interfaces;

/// <summary>
/// H3, F7, F8, E1 — Human approval gate compliance.
///
/// H3: EU AI Act Article 14 acknowledgement JSON for High/Critical risk tools.
/// F7: PendingApproval and OutboxMessage are created atomically (outbox pattern).
/// F8: ApprovalToken is a 256-bit CSPRNG token (64 hex chars, OWASP entropy minimum).
/// E1: Pipeline returns a suspended response with PendingInvocationId set.
/// </summary>
public sealed class ApprovalComplianceTests : IntegrationTestBase
{
    // ── Shared helper — configures discovery + gate for a high-risk tool ──────

    private void ConfigureHighRiskTool(Guid pendingId, string ns = "payments", string name = "charge")
    {
        var descriptor = new ToolDiscoveryDescriptor(
            Namespace:     ns,
            Name:          name,
            Version:       "1.0",
            Description:   "High-risk payment tool",
            WhenToUse:     "charge a card",
            WhenNotToUse:  "non-payment flows",
            NeedsApproval: true,
            ApprovalRisk:  ApprovalRisk.High,
            ApprovalReason: "Irreversible financial action — requires explicit human sign-off.");

        DiscoveryMock
            .Resolve(Arg.Any<string>(), Arg.Any<string>(), Arg.Any<string>(), Arg.Any<string>())
            .Returns(Result.Success(descriptor));

        GateMock
            .RequestApprovalAsync(
                Arg.Any<ApprovalContext>(),
                Arg.Any<string>(),
                Arg.Any<ApprovalRisk>(),
                Arg.Any<object?>(),
                Arg.Any<CancellationToken>())
            .Returns(ApprovalDecision.Suspend(pendingId));
    }

    // ── E1 — Suspended response ───────────────────────────────────────────────

    [Fact]
    public async Task SuspendedInvocation_Returns_SuspendedResponse_WithPendingInvocationId()
    {
        // Arrange
        var pendingId = Guid.NewGuid();
        ConfigureHighRiskTool(pendingId);
        await SeedTenantAsync(allowedNamespaces: ["*"]);
        var cmd = BuildCommand(toolNamespace: "payments", toolName: "charge");

        // Act
        var response = await Mediator.Send(cmd);

        // Assert — pipeline returns a suspended (202) response carrying the invocation ID.
        response.Success.Should().BeFalse(because: "suspended is not a success");
        response.PendingInvocationId.Should().Be(pendingId,
            because: "the ApprovalBehavior must relay the gate's PendingInvocationId");
        response.Error!.Code.Should().Be("APPROVAL_PENDING");
        response.Error.HttpStatusCode.Should().Be(202);
    }

    // ── F8 — ApprovalToken entropy ────────────────────────────────────────────

    [Fact]
    public void PendingApproval_ApprovalToken_Is64HexChars()
    {
        // Arrange — create a PendingApproval entity directly (domain test level)
        // to verify the token is generated by the CSPRNG factory, not Guid.NewGuid().
        var pending = ToolEngine.Core.Domain.Entities.PendingApproval.Create(
            correlationId:   Guid.NewGuid(),
            tenantId:        "acme",
            userId:          "user1",
            toolNamespace:   "payments",
            toolName:        "charge",
            toolVersion:     "1.0",
            serializedInput: "{}",
            channel:         ApprovalChannelType.Dashboard,
            risk:            ApprovalRisk.High,
            approvalReason:  "Requires approval",
            approverEmail:   null);

        // Assert — 256-bit CSPRNG → 32 bytes → 64 hex chars (OWASP minimum entropy).
        pending.ApprovalToken.Should().HaveLength(64,
            because: "token is Convert.ToHexString(RandomNumberGenerator.GetBytes(32)) = 64 hex chars");
        pending.ApprovalToken.Should().MatchRegex("^[0-9A-F]{64}$",
            because: "Convert.ToHexString produces uppercase hex");
    }

    [Fact]
    public void PendingApproval_TwoRecords_HaveDifferentTokens()
    {
        // Arrange — create two independent PendingApproval records.
        var a = ToolEngine.Core.Domain.Entities.PendingApproval.Create(
            Guid.NewGuid(), "t1", "u1", "ns", "tool", "1.0", "{}", ApprovalChannelType.Dashboard,
            ApprovalRisk.High, "reason", null);

        var b = ToolEngine.Core.Domain.Entities.PendingApproval.Create(
            Guid.NewGuid(), "t1", "u1", "ns", "tool", "1.0", "{}", ApprovalChannelType.Dashboard,
            ApprovalRisk.High, "reason", null);

        // Assert — tokens must be unique (collision probability ≈ 2^-256).
        a.ApprovalToken.Should().NotBe(b.ApprovalToken,
            because: "each approval token is generated by a CSPRNG and must be unique");
    }

    // ── H3 — Article 14 acknowledgement ──────────────────────────────────────

    [Fact]
    public void PendingApproval_SetAcknowledgement_StoresJson()
    {
        // Arrange
        var pending = ToolEngine.Core.Domain.Entities.PendingApproval.Create(
            Guid.NewGuid(), "acme", "user1", "payments", "charge", "1.0", "{}",
            ApprovalChannelType.Dashboard, ApprovalRisk.High, "reason", null);

        var ackJson = "{\"article\":\"14\",\"accepted\":true,\"operator\":\"alice\"}";

        // Act
        pending.SetAcknowledgement(ackJson);

        // Assert
        pending.AcknowledgementJson.Should().Be(ackJson,
            because: "H3 acknowledgement JSON must be stored verbatim");
    }

    [Fact]
    public void PendingApproval_SetAcknowledgement_IsImmutable_OnceSet()
    {
        // Arrange
        var pending = ToolEngine.Core.Domain.Entities.PendingApproval.Create(
            Guid.NewGuid(), "acme", "user1", "payments", "charge", "1.0", "{}",
            ApprovalChannelType.Dashboard, ApprovalRisk.High, "reason", null);

        var firstJson  = "{\"version\":\"1\"}";
        var secondJson = "{\"version\":\"2\"}";

        // Act
        pending.SetAcknowledgement(firstJson);
        pending.SetAcknowledgement(secondJson); // must be ignored

        // Assert — immutable once set (EU AI Act Article 14 non-repudiation).
        pending.AcknowledgementJson.Should().Be(firstJson,
            because: "acknowledgement is immutable once set — second call must be a no-op");
    }

    // ── Approval deny path ────────────────────────────────────────────────────

    [Fact]
    public async Task DeniedApproval_Returns403_ApprovalDenied()
    {
        // Arrange — gate denies synchronously.
        var descriptor = new ToolDiscoveryDescriptor(
            Namespace:     "payments",
            Name:          "refund",
            Version:       "1.0",
            Description:   "Refund tool",
            WhenToUse:     "refunds",
            WhenNotToUse:  "charges",
            NeedsApproval: true,
            ApprovalRisk:  ApprovalRisk.High);

        DiscoveryMock
            .Resolve(Arg.Any<string>(), Arg.Any<string>(), Arg.Any<string>(), Arg.Any<string>())
            .Returns(Result.Success(descriptor));

        GateMock
            .RequestApprovalAsync(
                Arg.Any<ApprovalContext>(),
                Arg.Any<string>(),
                Arg.Any<ApprovalRisk>(),
                Arg.Any<object?>(),
                Arg.Any<CancellationToken>())
            .Returns(ApprovalDecision.Deny("approver", "Rejected by policy"));

        await SeedTenantAsync(allowedNamespaces: ["*"]);
        var cmd = BuildCommand(toolNamespace: "payments", toolName: "refund");

        // Act
        var response = await Mediator.Send(cmd);

        // Assert
        response.Success.Should().BeFalse();
        response.Error!.Code.Should().Be("APPROVAL_DENIED");
        response.Error.HttpStatusCode.Should().Be(403);
    }

    // ── Approval allow path (no approval needed) ──────────────────────────────

    [Fact]
    public async Task ToolNotRequiringApproval_PassesThroughGate()
    {
        // Arrange — descriptor with NeedsApproval = false.
        var descriptor = new ToolDiscoveryDescriptor(
            Namespace:     "math",
            Name:          "calculate",
            Version:       "1.0",
            Description:   "Safe computation tool",
            WhenToUse:     "math",
            WhenNotToUse:  "payment",
            NeedsApproval: false);

        DiscoveryMock
            .Resolve(Arg.Any<string>(), Arg.Any<string>(), Arg.Any<string>(), Arg.Any<string>())
            .Returns(Result.Success(descriptor));

        await SeedTenantAsync(allowedNamespaces: ["*"]);
        var cmd = BuildCommand(toolNamespace: "math", toolName: "calculate");

        // Act
        var response = await Mediator.Send(cmd);

        // Assert — gate is never called; handler runs normally.
        response.Success.Should().BeTrue();

        await GateMock.DidNotReceive().RequestApprovalAsync(
            Arg.Any<ApprovalContext>(),
            Arg.Any<string>(),
            Arg.Any<ApprovalRisk>(),
            Arg.Any<object?>(),
            Arg.Any<CancellationToken>());
    }
}
